var materials=[],matches=[],approvedCodes=0;
var titles={dashboard:"Command Center",upload:"Upload Material Data",materials:"Material Catalog",matching:"AI Matching Engine",codes:"National Material Identity",validation:"Validation Center"};
function id(x){return document.getElementById(x)}
document.addEventListener("DOMContentLoaded",function(){
 document.querySelectorAll(".nav-item").forEach(function(b){b.onclick=function(){showPage(b.dataset.page)}});
 id("heroUpload").onclick=function(){showPage("upload")};id("heroDemo").onclick=loadDemoData;id("demoDataBtn").onclick=loadDemoData;id("loadDemoUpload").onclick=loadDemoData;
 id("chooseFileBtn").onclick=function(){id("csvFile").click()};id("csvFile").onchange=function(){id("fileName").textContent=this.files[0]?this.files[0].name:"No file selected"};id("processFile").onclick=processCSV;
 id("materialSearch").oninput=function(){renderMaterials(this.value)};
 var dz=id("dropZone");["dragenter","dragover"].forEach(function(e){dz.addEventListener(e,function(x){x.preventDefault();dz.classList.add("drag")})});["dragleave","drop"].forEach(function(e){dz.addEventListener(e,function(x){x.preventDefault();dz.classList.remove("drag")})});
 dz.addEventListener("drop",function(e){var f=e.dataTransfer.files[0];if(!f)return;var dt=new DataTransfer();dt.items.add(f);id("csvFile").files=dt.files;id("fileName").textContent=f.name;toast("File ready. Click Run AI Analysis.")});
});
function showPage(p){document.querySelectorAll(".page").forEach(function(x){x.classList.remove("active-page")});document.querySelectorAll(".nav-item").forEach(function(x){x.classList.remove("active")});id(p).classList.add("active-page");var b=document.querySelector('.nav-item[data-page="'+p+'"]');if(b)b.classList.add("active");id("pageTitle").textContent=titles[p]||"MaterialDNA AI";scrollTo({top:0,behavior:"smooth"})}
function processCSV(){var input=id("csvFile");if(!input.files.length){status("Please select a CSV file first.",false);return}var r=new FileReader();status("Reading and analysing material records...",null);r.onload=function(e){parseCSV(e.target.result)};r.onerror=function(){status("The file could not be read.",false)};r.readAsText(input.files[0])}
function parseCSV(text){var lines=text.replace(/^\uFEFF/,"").split(/\r?\n/).filter(function(x){return x.trim()});if(lines.length<2){status("CSV needs a header and at least one data row.",false);return}var h=parseLine(lines[0]).map(function(x){return x.trim().toLowerCase()});var ci=findHeader(h,["cpse","organization","company"]),co=findHeader(h,["material code","materialcode","code","legacy code"]),di=findHeader(h,["material description","materialdescription","description","material name"]);if(ci<0||co<0||di<0){status("Required columns: CPSE, Material Code, Material Description",false);return}materials=[];approvedCodes=0;for(var i=1;i<lines.length;i++){var v=parseLine(lines[i]),a=(v[ci]||"").trim(),b=(v[co]||"").trim(),c=(v[di]||"").trim();if(a&&b&&c)materials.push({cpse:a,code:b,description:c,normalized:normalize(c)})}if(!materials.length){status("No valid material records found.",false);return}findMatches();renderAll();status(materials.length+" records analysed successfully. "+matches.length+" AI recommendations generated.",true);toast("Analysis complete — "+matches.length+" recommendations found.")}
function parseLine(line){var r=[],c="",q=false;for(var i=0;i<line.length;i++){var x=line[i];if(x==='"'){if(q&&line[i+1]==='"'){c+='"';i++}else q=!q}else if(x===","&&!q){r.push(c);c=""}else c+=x}r.push(c);return r}
function findHeader(h,a){for(var i=0;i<h.length;i++)if(a.indexOf(h[i])>-1)return i;return-1}
function normalize(t){return t.toLowerCase().replace(/[×x]/g," x ").replace(/[^a-z0-9.\s]/g," ").replace(/\bbrg\b/g,"bearing").replace(/\bbearings\b/g,"bearing").replace(/\s+/g," ").trim()}
function numbers(t){return t.match(/\d+(?:\.\d+)?/g)||[]}
function similarity(a,b){var A=new Set(a.split(/\s+/).filter(Boolean)),B=new Set(b.split(/\s+/).filter(Boolean)),n=0;A.forEach(function(x){if(B.has(x))n++});var u=new Set(Array.from(A).concat(Array.from(B))).size,s=u?n/u*100:0,na=numbers(a),nb=numbers(b),common=na.filter(function(x){return nb.indexOf(x)>-1}).length;if(common)s+=Math.min(30,common*10);if(a.includes("bearing")&&b.includes("bearing"))s+=10;return Math.min(100,Math.round(s))}
function findMatches(){matches=[];for(var i=0;i<materials.length;i++)for(var j=i+1;j<materials.length;j++){if(materials[i].cpse.toLowerCase()===materials[j].cpse.toLowerCase())continue;var s=similarity(materials[i].normalized,materials[j].normalized);if(s>=40)matches.push({material1:materials[i],material2:materials[j],score:s,status:"pending"})}matches.sort(function(a,b){return b.score-a.score})}
function renderAll(){renderDashboard();renderMaterials(id("materialSearch").value||"");renderMatches();renderCodes();renderValidation()}
function renderDashboard(){var set=new Set(materials.map(function(m){return m.cpse}));id("totalMaterials").textContent=materials.length;id("duplicateCount").textContent=matches.length;id("cpseCount").textContent=set.size;id("approvedCount").textContent=approvedCodes;id("heroMaterials").textContent=materials.length;id("heroMatches").textContent=matches.length;id("heroCpse").textContent=set.size;var names=Array.from(set);document.querySelectorAll(".node").forEach(function(n,i){n.textContent=names[i]||"CPSE"});if(materials.length)id("activityList").innerHTML=activity("↥","Data uploaded",materials.length+" material records ingested")+activity("⌘","AI matching completed",matches.length+" recommendations generated")+activity("#","Identity engine ready","Legacy codes preserved for validation")}
function activity(i,t,s){return '<div class="activity"><i>'+i+'</i><div><b>'+esc(t)+'</b><span>'+esc(s)+'</span></div></div>'}
function renderMaterials(q){q=(q||"").toLowerCase();var f=materials.filter(function(m){return !q||(m.cpse+" "+m.code+" "+m.description+" "+m.normalized).toLowerCase().includes(q)});id("materialCountLabel").textContent=f.length+" record"+(f.length===1?"":"s");id("materialsTable").innerHTML=f.length?f.map(function(m,i){return "<tr><td>"+(i+1)+"</td><td>"+esc(m.cpse)+"</td><td>"+esc(m.code)+"</td><td>"+esc(m.description)+"</td><td>"+esc(m.normalized)+"</td></tr>"}).join(""):'<tr><td colspan="5" class="empty-row">'+(materials.length?"No records match your search.":"No material data yet. Upload a CSV or load the demo dataset.")+"</td></tr>"}
function renderMatches(){var c=id("matchesContainer");if(!matches.length){c.innerHTML='<div class="empty-state">'+(materials.length?"No recommendations crossed the 40% similarity threshold.":"Upload data to activate the AI matching engine.")+"</div>";return}c.innerHTML=matches.map(function(m,i){return '<article class="match-card"><div class="match-top"><div><h3>Harmonization Candidate #'+(i+1)+'</h3><p>Cross-organization material identity recommendation</p></div><div class="match-score">'+m.score+'% match</div></div><div class="pair-grid">'+chip(m.material1)+chip(m.material2)+"</div></article>"}).join("")}
function chip(m){return '<div class="material-chip"><small>'+esc(m.cpse)+" · "+esc(m.code)+'</small><b>Original material</b><p>'+esc(m.description)+"</p></div>"}
function national(m,i){var w=(m.material1.normalized.split(" ")[0]||"mat").slice(0,3).toUpperCase(),n=numbers(m.material1.normalized)[0]||String(i+1).padStart(3,"0");return "NMID-"+w+"-"+n+"-"+String(i+1).padStart(3,"0")}
function renderCodes(){var c=id("codeContainer");if(!matches.length){c.innerHTML='<div class="empty-state">AI recommendations will appear here after analysis.</div>';return}c.innerHTML=matches.map(function(m,i){return '<article class="code-card"><p class="eyebrow">RECOMMENDED IDENTITY</p><h3>Common material identity</h3><div class="code-value">'+national(m,i)+'</div><div class="legacy-list"><div class="legacy-code">'+esc(m.material1.cpse)+": "+esc(m.material1.code)+'</div><div class="legacy-code">'+esc(m.material2.cpse)+": "+esc(m.material2.code)+"</div></div></article>"}).join("")}
function renderValidation(){var c=id("validationContainer");if(!matches.length){c.innerHTML='<div class="empty-state">No recommendations available yet.</div>';return}c.innerHTML="";matches.forEach(function(m,i){var card=document.createElement("article");card.className="validation-card";card.innerHTML="<h3>Recommendation #"+(i+1)+"</h3><p><b>"+esc(m.material1.description)+"</b></p><p>↕</p><p><b>"+esc(m.material2.description)+"</b></p><p>AI confidence: <b>"+m.score+"%</b> · Status: <b>"+m.status+"</b></p>";if(m.status==="pending"){var a=document.createElement("div");a.className="validation-actions";var ok=document.createElement("button");ok.className="approve-button";ok.textContent="Approve Identity";ok.onclick=function(){m.status="approved";approvedCodes=matches.filter(function(x){return x.status==="approved"}).length;renderAll();toast("Identity approved successfully.")};var no=document.createElement("button");no.className="reject-button";no.textContent="Reject";no.onclick=function(){m.status="rejected";approvedCodes=matches.filter(function(x){return x.status==="approved"}).length;renderAll();toast("Recommendation rejected.")};a.append(ok,no);card.append(a)}c.append(card)})}
function status(m,s){var e=id("uploadStatus");e.textContent=m;e.style.color=s===true?"#66e8a7":s===false?"#ff8a96":"#66d8ff"}
function loadDemoData(){materials=[["IOCL","IOCL-101","Deep Groove Ball Bearing 6205 SKF 25x52x15 mm"],["BPCL","BPCL-501","Ball Bearing SKF 6205 25 x 52 x 15 mm"],["HPCL","HPCL-202","Deep Groove Bearing 6205 SKF"],["ONGC","ONGC-888","Bearing 6305 SKF 25x62x17 mm"],["GAIL","GAIL-331","Stainless Steel Hex Bolt M16 x 60 mm"],["HAL","HAL-117","SS Hex Head Bolt M16 60mm"],["SAIL","SAIL-770","Industrial Gate Valve 2 inch Carbon Steel"]].map(function(x){return{cpse:x[0],code:x[1],description:x[2],normalized:normalize(x[2])}});approvedCodes=0;findMatches();renderAll();showPage("dashboard");toast("Live demo dataset loaded.")}
function esc(v){var d=document.createElement("div");d.textContent=String(v);return d.innerHTML}
function toast(m){var e=id("toast");e.textContent=m;e.classList.add("show");clearTimeout(window.t);window.t=setTimeout(function(){e.classList.remove("show")},3000)}